/**
 * How far each region of Azhora has actually been built, for the developer's
 * chart. The playable regions differ a great deal: Drent is finished ground,
 * Luscia and the Moros carry their chapters but little else, West Suval and
 * Pueth are new, East Suval is a shut border and nothing behind it. Everything
 * else on the atlas is unbuilt. Keep this honest; it is the map of the work
 * left to do. Pure: no DOM, no three.
 */
import { PLAYABLE_REGIONS } from './region-layout.js';
import { REGION_DESIGN } from './campaign-world.js';

/** The states a region can be in, worst first, each with the colour the developer chart tints it. */
export const BUILD_STATES = Object.freeze({
  unbuilt: Object.freeze({ id: 'unbuilt', label: 'Not built', order: 0, colour: '#6d6f68', note: 'Charted only. There is no ground to walk.' }),
  edge: Object.freeze({ id: 'edge', label: 'Edge only', order: 1, colour: '#b4703a', note: 'You can reach its border and no further.' }),
  environment: Object.freeze({ id: 'environment', label: 'Environment preview', order: 2, colour: '#849a63', note: 'Walkable terrain, habitats and exterior structures. Regional gameplay and interiors remain incomplete.' }),
  early: Object.freeze({ id: 'early', label: 'Playable · early', order: 2, colour: '#c8a53f', note: 'Walkable, with its main places built and a good deal still missing.' }),
  playable: Object.freeze({ id: 'playable', label: 'Playable', order: 3, colour: '#8fae4f', note: 'Walkable, with its chapter, its people and its places.' }),
  built: Object.freeze({ id: 'built', label: 'Built out', order: 4, colour: '#5f9e63', note: 'Finished ground: places, people, work, wildlife and detail throughout.' }),
});

const status = (state, detail, work) => Object.freeze({ state, detail, work });
const ibenwoodWork = 'Ranger patrol tuning and stealth-route refinement continue. Permission quests, Elfland withdrawal, magical fauna, building interiors, civilian communities, royalty and broader regional quests remain incomplete.';
const ibenwoodDefense = ' Persistent rangers defend the signed inner belt around Elfland, with physical arrows and skill-sensitive stealth entry.';

/** Region by region. `detail` is what exists; `work` is what it still wants. */
export const BUILD_STATUS = Object.freeze({
  Yunethre: status('early', 'Open steppe and wooded hollows surround a mixed lakeside free town and Bane’s tent-and-wagon camp. Human, elven and centaur peacekeepers explain the town’s neutrality; centaur warriors defend their plains, and a persistent patrol raids northwestern Isareos and returns to camp. Fifty resident animals occupy the countryside.', 'Trade, civilian stories, faction permissions and the wider centaur campaign remain unfinished.'),
  'South Oremindi Mountains': status('environment', 'Environment preview: the authored hill approaches and high mountains, two alpine lake basins, tundra and permanent ice, with grounded regional vegetation and wildlife.',
    'Sevron, other settlements, the sage and the campaign convergence chapter remain unbuilt. No civilian population, interiors, trade, pass infrastructure or regional quests.'),
  'East Ibenwood': status('environment', 'Environment preview: atlas-shaped ancient woodland, denser wild forest around the established elven grove, root and branch dwellings and old stone exteriors, selected accessible canopy platforms, forest paths and ordinary wildlife.' + ibenwoodDefense, ibenwoodWork),
  'North Ibenwood': status('environment', 'Environment preview: atlas-shaped northern woodland, varied forest habitats, dense patches among passable trees, the exterior dwellings of Cedar Root Hollow, woodland approaches and ordinary wildlife.' + ibenwoodDefense, ibenwoodWork),
  'South Ibenwood': status('environment', 'Environment preview: atlas-shaped southern forest, denser wild woodland and paths, ordinary wildlife, and the authored river running south from Central Ibenwood with visible water and a carved channel.' + ibenwoodDefense, ibenwoodWork),
  'West Ibenwood': status('environment', 'Environment preview: atlas-shaped western woodland, Mossbound Stone Boughs and its exterior dwellings, selected accessible canopy platforms, ordinary wildlife and the short authored stream on the western border.' + ibenwoodDefense, ibenwoodWork),
  'Central Ibenwood': status('environment', 'Environment preview: the forest heart of Elfland, High Bough Grove and a reserved royal clearing separated by ancient woodland, selected accessible canopy platforms, ordinary wildlife and the authored river toward South Ibenwood.' + ibenwoodDefense, ibenwoodWork),
  Drent: status('built', 'Tidehaven and its landing, the Greenway woods and their small places, Willowmere, the Avrel clearings, the road to the Caloss, the road north to the Tessen, the old Rena road with the ruins of Rena and Applegarth on it, deer, birds, insects and forage, the birding skill and Jean’s bird garden.',
    'Nothing urgent. The southern farms and the coast north of the pier are still empty, and the old road gives out west of Applegarth.'),
  Luscia: status('playable', 'The Caloss crossing, the reedcutters, the rise, the field at the Lauvel and its chapter, Nothom with the smiths, the relay clerk and the stable yard.',
    'The town is thin: few interiors, no market, no work to do. The valleys east and west are scatter and landmarks only.'),
  'Moros Plain': status('playable', 'The army camp at the plain’s centre with its gate, tents and horse lines, the open road from Nothom, the border stockade and the battle ground.',
    'Open plain between them. No settlements, no work, nothing off the road.'),
  'West Suval': status('early', 'Solis: walls, gates, the Court of Oaths, the quay and the Coalition’s camp, with the parley, the march and the day after the battle. The road from the border, the fold, the watchtower and the well.',
    'The downs are scatter. The city has no interiors and no trade; the coast south of the quay is unbuilt.'),
  Pueth: status('early', 'The Tessen crossing with its bridge and army road post, the bramble woods and the goblin camp, Rimeholt on the Feradom road, and the two rivers the atlas authored.',
    'Rimeholt is a first version. The hills, the east and the coast are terrain and landmarks only; no quests of its own.'),
  Peblos: status('early', 'The boat from Tidehaven’s pier and back for three copper, Cobble on the main island with its quay, its ten roofs, its seven islanders and the Empire’s four men, the headland light, the seal cove and the drowned field.',
    'The five outer islands are terrain, scatter and one landmark each, with no way to reach them. No quest, no naval station, no sea cave, no pirates, and nothing to buy or sell on the quay.'),
  'West Izol': status('early', 'Izolveth on its cut terrace: the Long Quay, two moles and a boom, five ships, the warehouses and the ropewalk, the meeting house and the Stone of Izol, twenty-five people, the Coalition’s camp and drill ground above the town, Ardveth, the boatyard at Kelvath Cove, the Sea Gate and the Sightstone.',
    'No chapter: the Republic branch of Chapter 3 is where the choice among the three generals belongs, and none of it is wired. No voyage in or out, no interiors, no trade, no quest, and the interior south and east of the Long Pasture is terrain, scatter and one landmark.'),
  Elagos: status('early', 'Ambron on the Lake Ela narrows: four ages of wall on one closed circuit, the causeway over the water, the chain in the south water gate, the quays and the toll house, the Lord Marshal’s Seat, and thirty-two people in the city and the lake country, five of them the city’s specialists in the skills Drent teaches, one of whom sends the traveler after the last talking tree. The lakes themselves, the Ela-south, the Stair, Nemmel, the ice-road stone, the lake shrine and the drowned causeway.',
    'Chapter 3 is not built: nobody here moves a quest and the city cannot be arrived at except by the haul road. No interiors, no market to trade in, no lake fleet, and Brul, Ossen and the Thelas chain are water and landmarks only.'),
  Amod: status('early', 'The east end only: the road in from western Pueth, the pass stones and the ogre who takes a toll on them, terraces cut into the ground itself from the Tarvel up to the chestnut line, Ostel on its shoulder with its water court, press, cellars, stonecutters’ yard and seventeen people, the burial terrace above it, Vessen, and the Tarvel with its bridge, its head and the Dromel gate.',
    'Everything west of the Ostel bridge: Kelmod, Sareth-am-Vel, Tir Amel and Mavren are names on signs. No chapter of its own, no trade, no interiors, and the water court hears no case the traveler can take part in.'),
  // The western terrain remains early. Vastos now has one local silver quest;
  // the other three regions still await their communities and travel routes.
  Vastos: status('early', 'The cold tableland itself: flat upland grass above both its approaches, the Vastos River braiding across the south, the snowmelt beck off the Amod margin, five watering pans on the open range, sulfur ground with three vents on the western fall, two small lake basins on the eastern one, and longhorn cattle, hares and a hawk over the grass. The Common Water is one small herders’ camp with three people and the first Ambroni Civil War silver quest: return the strays, reopen the water and settle a local Republican, Monarchist or negotiated claim.',
    'The rest of its communities and travel network. No winter quarters, no river crossings, no vel-vastos routes, and no way in from Elagos or Amod but open country. The camp settles one watering route, not the province or the war.'),
  Meneth: status('early', 'The ridge country itself: parallel ridges running east and west with an open valley between each pair, a beck on every valley floor draining east to the Vastos River, hay meadow on the floors, wild chestnut and walnut on the lower faces, close-grown hardwood above, and sheep and hares on the commons.',
    'Everybody, and the routes they live off: the Southern Lotharn Road, the junction communities on it, the elder assemblies, and every crossing of every ridge. The ridges themselves give out southward into the lake country with nothing built on that ground.'),
  Caricas: status('early', 'The Carica corridor retains its old-growth river woodland, stony eastern shelf, deep Lizeem and quick Carica, with river foxes and otters. An Imperial market town, garrison and five cultivated farmsteads now occupy the dry shelf. Garden beds, local seed stores and lanes use the existing farming skill; a public road reaches Menora by the White Bridge.',
    'The region is fully occupied by the Ambroni Empire. Its civil-war side story remains reserved; no additional civilians, completed regional quest, trading system or interiors have been invented.'),
  Nesdor: status('early', 'The transition out of the branch country: shallow broad valleys with hazel and oak on their slopes in the north-west, and east and south of them the Flats — dark alluvial ground with almost no relief on it, two shallow watercourses braiding across it into the Lizeem (one of them the Ela-south, which the atlas hands into this region and which nobody’s lore mentions), the great river along the southern edge, and cattle, sheep and waders on all of it.',
    'Everybody, and the trade that is the whole point of the place: the Nesdor Way, the route-communities on it, the inns and warehouses and stables, and the legal practitioners who sell the difference between Branch Compact law and open country. The army’s rope line out of the Moros still stands across the Flats: an Ambroni line inside a country the Empire does not hold.'),
  // The first of the six south-western countries, and terrain and wildlife only like the four
  // before it. It is the only one of the six a traveler can walk to: the Lizeem is a wall and
  // Eer is the one country on this side of it.
  Eer: status('early', 'The plain between the great river and the sea, and the place the green country ends: black alluvial loam and rank damp grass in the humid north-west, dry tawny grass, cushion scrub and standing wild olives on the Mediterranean coast, the change happening in the middle of the country rather than at a border. The Lizeem’s last reach along the western edge, unfordable like every metre of it above; two channels braiding across the plain to a low shore of small bays; alder and willow on their upper halves and tamarisk and oleander on their lower; herons, egrets, stilts and duck on the water, boar in the scrub, gulls on the shore and grey dolphins out past the surf. The first country in the game with a sky of its own.',
    'Everybody, and everything they have built: the villages, the canal systems and the drainage the lore is really about, the north road out of Nylon and the customs every occupier in eleven occupations has taxed on it. Nylon itself is off the atlas. No quest, no chapter, no way over the Lizeem to Gala, and the five countries on the far bank of it are not built.'),
  // Menora keeps its historic river fork; the new bridges are physical crossings.
  Isareos: status('early', 'Menora is an intact, fortified holy city on the Isa-Lizeem fork: tall white walls, four open gates, river bridges, garden streams, houses, a grand temple and a 128-metre Sorcerers\u2019 Guild tower. Prince Cedric lives at the temple court; Prince Wilhelm and his army muster outside the western gate. The surrounding grass hills retain their becks, river galleries, deer, hares, otters and vultures. A persistent centaur raiding band travels from Yunethre into the exposed northern and western frontier.',
    'Cedric and Wilhelm have introductory conversations but their Chapter 3 or 4 story is deliberately unfinished. Guild training, temple interiors, civilian communities, trade and wider frontier quests remain to be designed. Menora and the independent Yunethre town are protected from the raiding route.'),
  // The third of the six, and the one the atlas took a whole country away from: it has no
  // `lake` hex and no `wetland` hex, so there is no Nethermere and no marsh round it. What is
  // built is the shape the lore's mechanism describes and the pasture the flood leaves.
  Nethereum: status('early', 'The wet grass country between the Isa and the Neth: a broad shallow hollow six hundred metres across and eight deep, with the fall spread over two hundred paces so that nothing about it is a bank. Rank wet meadow on its floor — the greenest ground in the game — ordinary humid grass up the sides and over the rim, wet threads of rush and sedge where three hill-streams give their channels up on the floor, and a gallery of willow and alder on the water and nowhere else. The Neth along the southern border, waded in its upper third and deep below it, which is the only dry way between this country and Ovesos; the Isa along the northern one; the Lizeem deep along the east; the atlas’s own small outlet carrying the basin south-east to the Neth’s head. Nethrani cattle loose on the floor, hares on the dry rim, otters on the deep Neth, three herons on the threads and a harrier quartering the meadow. The second country in the game with a sky of its own, and it asks for the opposite of Eer’s.',
    'Everybody, and everything the flood organises: the ridge and hummock communities, the Flood Council, the Flood Recall, the fish weirs, the levees, and the oats and hay off the flood meadow, which are crops and are somebody’s. The flood itself is not built either — the game has no seasons to bring it, so what is shown is the dry state all year. No chapter, no quest; the Nether Desert on the west and Ovesos across the ford are not built.'),
  // Terrain, wildlife and one city's stones (the user, 25 September 2026: build the physical
  // terrain and climate, the wildlife and Imlamdris's infrastructure, and no characters yet).
  'South Suval': status('early', 'The Stillwater, its shores and wildlife remain. Above it rise tall limestone peaks with narrow graded switchbacks and solid cliff faces. The Blood Prince razed Imlamdris: sixteen roofless homes and the ruined Stillwater Temple remain beside four small wooden rebuilding homes and a fifth frame. The vigilante shelters in a traversable cave on Hollow Ridge. Burned trees and abandoned Nanvir offering stones scar the southern country.',
    'Everybody in the rebuilding settlement still awaits deliberate character design. No interiors or ordinary flight mounts. The East Suval gates remain barred; the original hill road still reaches them.'),
  'Iscare Archipeligo': status('early', 'Ten authored island hexes, low rock spines, coastal scrub, wind-bent trees, hares and seabirds. The abandoned port of Zecron has twelve roofless buildings, a broken lighthouse and burned quay piles. Five smaller island settlements carry fifteen more burned shells.',
    'No residents, ferry service, boating controls, interiors or regional quest. The islands can be inspected with testing travel or the developer bat.'),
  // Ground, water, forest, wildlife and three made places, no characters (the user, 26 September
  // 2026: "start building the East Lotharn Mountains based on the lore").
  'East Lotharn Mountains': status('early', 'The old range north of Amod, and a high one: four peaks, the eastern four hundred and twenty metres, each ringed by cliffs in courses thirty-six metres high with ledges between, climbed by ramps cut slantwise across the cliffs and by chimneys through them; eight caves to explore, and a passage right through from Kemrath to Upper Olveth. Forested on the ledges and the valley floors nearly to the tops in oak, chestnut, maple, beech, hickory, walnut and tulip poplar, with grazed balds on the two massifs. Kemrath, the broad flat-floored high valley under the central massif, its water running west, fields in strips down both sides of it and vines on its north wall; the col at its head, the divide and the pass’s highest section, with the pass inn on it; Stonegate, the gorge the road goes down, white water between walls of tilted limestone, shale, sandstone and coal, with shells in the stone at its head; Upper Olveth, the open high valley of the north face, with sheep grass and a dry-stone fold; the iron workings above Kemrath, the first ore left at the portal with bread and salt; and the border water along the northern foot, running east to the sea. The pass road from Amod’s notch over the col and down Stonegate to the border water. Deer on the central bald and boar at the wood’s edge, herons on the Kemrath water, sheep on Olveth, hares on the balds, a hawk over the ridge. Its own sky.',
    'Everybody: the valley people, the pass families who keep the inn, the miners and their guild, the fossil readers. The three corners of the Empire’s survey - the rebels, the goblin warrens and the orcs’ trail - and the wolves, trolls and giants of the level-three range. The descent from the notch into Amod, which the Amod lore gives to Sareth-am-Vel, and the Mithala plain beyond the border water: the road stops at both.'),
  // The barrier hills and their fortresses, and the Duchy's own army in them (the user, 27 September
  // 2026: "start building the Feradom region... the hills... obstacles but not mountains, and lining the
  // border with fortresses"). 'edge' like East Suval: the border is shut, and the way in is F8.
  Feradom: status('edge', 'The barrier hills along the whole inland edge, from the Ordel to the East Lotharn: a talus slope and a band of exposed rock toward the border that uses the climbing skill, rolling forested hills behind in two rows of summits, a few gullies a determined traveler can scramble up, and a gentle back slope to the coast. Oak and fir, old on the tops and managed in stands below. Six passes, each a gorge with a tower above the narrows and a castle filling the basin behind it, its gate toward the border shut; the great castle at the Road Pass, where the Feradom road comes up from the army’s barrier in Pueth; beacons on the summits between. The Duchy’s own army in the castles and on the towers, in their own kit: mail to the knee, the duchy’s russet, the green of the hills, a nasal helm and a kite shield. Resident deer, boar and hares throughout all thirty-four hexes, and a hawk over the hills. Seven farms on the coastal plain have irregular fields, orchards, narrow lanes and workable garden beds.',
    'Everything behind the hills: the lords’ valleys, the harbour towns in their coves, the rocky headlands and the cold coast, the fishing fleet, the timber trade; the lords and the pass-lords themselves. The border is closed, so the only way in is the F8 tools.'),
  // Terrain, climate, water and wildlife, and nothing that belongs to anybody (docs/gala-brief.md). The
  // far bank of the Lizeem: nobody walks here from Eer, and the dry ways in are from open country.
  Gala: status('early', 'The western bank of the Lizeem near its mouth, one plain with three climates laid across it: hot steppe on the northern rows, bunch grass in tussocks, grey wormwood and saltbush and a dry gravel wash that runs only in the rains; tawny Mediterranean grass in the middle with low maquis on the rises and wild olive and fig standing singly; and a short coast where the plain’s own water comes down to the sea in braided mouths through reed and tamarisk. The Oveth along the north, fordable over rock at its head and deep below; the Caelin, a shallow stream off the Oves Desert; the Treloss, a small one down the Telemonia border to the sea; the Lizeem along the east, unfordable. Black geese on the mouths, stilts and egrets on the water, herons on the reed bank, gulls and dolphins at the shore, hares, a harrier and a hawk over the steppe, boar in the maquis.',
    'Everybody, and everything they have built: the city of Gala, its harbour, its market and the Guild of Assessors, the council hall with its Avite bronze, the herding communities of the north and the irrigation channels the lore gives the dry stretches. No quest, no chapter. The seam with Northern Ascarth is being built in another branch; Ovesos, the Oves Desert, Telemonia and Legemum are open country, and Nylon is not on the atlas.'),
  // Terrain, climate, water and wildlife only, nobody's (the user, 28 September 2026: "start building the
  // wildlife and terrain of Galan, North Ascarth, and South Ascarth"). 'early', as Eer is. Both are on
  // the far bank of the Lizeem: the way in on foot is through Gala.
  // Ovesos and the Oves Desert (docs/oves-brief.md): terrain, climate, water, scenery and wildlife
  // only. Both read `BSh` on every hex, so the difference between them is terrain and water.
  Ovesos: status('early', 'The middle Oveth as a hot steppe: upland bunch grass in tussocks over the northern rows with the bare earth showing between them, six metres above the river; thinner open plain below, with grey wormwood and saltbush where the grass gives out and stones on the rises. The Oveth along the whole south-western border \u2014 waded over gravel at its head, deep through the Sorten, the bench of bottomland it slows and spreads on \u2014 with a gallery of poplar, willow and tamarisk on it and no other tree in the country. One dry gully off the grass shoulder. The Neth along the north-west, waded in its upper third; the Lizeem along the north-east and east, unfordable. Otters, ducks, herons and the vel-caric on the river, hares and a harrier on the upland grass, a vulture over the dry plain.',
    'Everybody, and everything they have built or argue about: the Water Council and every water right it allocates, King Melos and the house Oveth-Hold, the Middle Reach dispute with Nescor, the Branch Court, the market towns, the mills on the upper river, the irrigated bottomland grain and the channels that water it, the upland herding communities and all their stock. No quest, no chapter; Nescor, Isoruous and Telemonia are not on the playable atlas.'),
  'Oves Desert': status('early', 'The far tail of the Pyros rain shadow, and rocky rather than sandy: a wedge of the Oveth basin falling from the rim hills in the north-west to its point in the east, worn stone through a thin poor soil, gravel pavement wherever the rock is up, perennial scrub spaced wide enough to walk between, and a stubble of dead annual seed-heads in the pockets \u2014 the wet-year flush as a dry year leaves it. Three low rounded hills on the rim intercept what moisture the westerlies carry, and the Caelin runs along the whole southern border, waded anywhere. Three cut channels run off their feet with no water in any of them, and one reach of one holds water under the gravel: a hundred paces of scrub and two tamarisk, the only green in the country. Hares on the scrub, the dry-plateau hawk over the rim, a vulture over the wedge, and nothing else at all.',
    'Everybody who is ever in it, and all of them from somewhere else: the Ovesos pastoral communities who graze it in wet years, the Telemon bands who keep the southern routes, the wells and the watering points on them, and the Branch Compact classification dispute the whole country is famous for. No permanent water is built because it has none. No quest, no chapter; East Pyros, Telemonia and the Nether Desert round it are open country.'),
  'Northern Ascarth': status('early', 'The neck and the highland interior of the Ascarth Peninsula: low grass at Gala’s level where it joins the mainland, then a rugged plateau of tawny Mediterranean grass, aromatic scrub and stone rising out of it, and the interior hills - two rounded rocky hills and the shoulder of a third, wooded in evergreen oak with pine on the tops, with green copper stain on the south hill’s stone. Cliffs along the western shore with gulls on them; on the east the ground falls to sheltered bays between low cliffed headlands, the north bay under the Lizeem’s mouth. Red deer on the saddle between the hills, boar at the wood’s edge, hares on the plateau, a hawk over the wood. Csa on the grass and Csb on the hills, and its own clear sea-air sky.',
    'Everybody. Aevis and its citadel, the bronze gates and the bull-headed figures, the harbour, the veth and their archive, the smiths’ guild, the burial mounds and the copper workings: none of it. No way in from Eer - the one edge it shares with Eer is the Lizeem’s last - and Gala, the way in, is its own job.'),
  // The West Lotharn (docs/west-lotharn-brief.md, docs/west-lotharn-report.md): terrain, climate,
  // water, scenery, caves and wildlife only, and nothing that belongs to anybody. The East Lotharn's
  // pass road, inn and iron workings are not copied: that half was built to an earlier brief.
  'West Lotharn Mountains': status('early', 'The spine of the Lotharn, and its taller half: one great massif with the crest at five hundred and fifty metres, the north summit at four hundred and forty-eight, the west shoulder at four hundred and four and the east summit at three hundred and twenty, and three lesser masses round it — the south-east spur, the cold head at the western tip and the south rampart over Isareos. Asymmetric shoulders and buttresses rise in courses of cliff, with patchy old forest on the shelves and pale grass on the summit crowns; slanting ramps and ledge paths offer routes up, as do the nine caves — five chimneys through the cliffs, three chambers, and the passage under the east arm from the col to the long valley. Nothing lives in any of them. The long valley crosses the whole range from the Vastos margin to the hills above Yunethre, flat-floored and grown over, with a divide a fifth of the way along it and a beck leaving each end; the north valley drains the massif to the Mithala plain; and the col at the east end is where the two halves of the range join, with the Kemrath water coming out of the East Lotharn through it and turning north down the notch. Oak, chestnut, maple, beech, hickory, walnut and tulip poplar on the ledges to three hundred and forty-five metres, then bare stone. Deer and boar on the valley floors, the vel-caric on the west beck, herons on the reach, hares on the crest’s and the cold head’s balds, a vulture over the crest and a hawk over the west shoulder. Its own thin, clear sky.',
    'Everybody, and everything in the lore that is theirs: every valley community and its dialect, the mining districts, the iron and coal and copper, the pass inns and the waypoints, the field, the wall, the track and the burning of the ridge-tops. No road and no pass are built — the atlas gives this half neither — and there is no quest and no chapter. South Celder and South Mithala remain open country. Yunethre now has its own steppe, neutral lakeside town and centaur camp below the western approach.'),
  'Southern Ascarth': status('early', 'The finger of the peninsula to its tip: open Mediterranean grass and scrub on a thin, stony plateau between two seas, a wild olive standing alone here and there, cliffs along the whole of the west and round the tip with rock fallen at their feet, and two sheltered bays with beaches on the east. Hares on the grass, gulls on the tip’s cliffs, a harrier quartering toward the tip, grey dolphins off the east shore, and sea-plungers folding into the water off the tip. Selemi across a narrow channel to the south.',
    'Everybody: the small southern cities outside Aevis’s reach, their poor harbours and their archaic Avite, and their own warrior lines. No quest, no chapter, and nothing reaches it but through Northern Ascarth.'),
  // Selemi, the island across the channel from that tip (docs/selemis-brief.md, docs/selemis-report.md):
  // terrain, climate, water, scenery and wildlife only. Almost everything its lore has is the city,
  // and the city is somebody's.
  Selemi: status('early', 'The island of Selemis: eight hexes of hot-summer Mediterranean grass a channel’s width south of the Ascarth tip, and a crescent with its hollow turned on the peninsula. One sheltered bay in the hollow - the Seloca, which is the Selemi word for a harbour - with a strand of sand round three sides of it and a rocky head at either end; behind the strand a hollow of greener ground climbing to three grass hills along the island’s back, the highest twenty-seven metres up; beyond them the ground tilting on up toward the open sea and ending in thirteen metres of pale cliff. Every shore but the bay’s is a cliff. Straw grass, aromatic scrub and pale stone, a few pines leaning in the lee of the hills, tamarisk and sea-wrack on the strand, two dry winter beds and no stream or spring. Gulls on both heads, sea-plungers off the ocean face, grey dolphins in the lane past the eastern end, and the peninsula’s own clear sky. The channel - the Nocveth, a crossing - is sixty metres of deep water at its narrowest.',
    'Everybody, and nearly everything the lore has: the city of Selemis that fills the crescent from headland to headland, its harbour works and fortifications, the fast ships kept in the channel, the warehouses, the archive, the outposts it runs - and the Izoli garrison that has held it since 979. No building, no quay, no road, no ship, no person, no quest, no chapter. Nothing reaches the island but the water: no ferry runs to it, and whether the channel should be swum is the user’s to decide (docs/selemis-report.md).'),
  // The Mithala plain: four countries built as one job (docs/mithala-brief.md, docs/mithala-report.md),
  // terrain, climate, water, scenery and wildlife only, and nothing that belongs to anybody.
  'South Mithala': status('early', 'The plain’s southern march, with both halves of the Lotharn along its whole southern border: flat dark grain country between the mountains’ border water and the main channel, the meeting of the two arms at its north-western corner where every drop of water on the plain passes, four low swells of the Lotharn’s last apron at twenty-four metres, levees a pace and a half high on the channel banks with backswamps behind them, and one dry summer channel. Red deer and frostback buffalo on the open grass, boar in the gallery, otters and herons on the water.',
    'Everybody. The lore of this plain is villages on their levees, the flood calendar, the water courts, the channel affiliations that are the people’s whole spatial identity, the grain that feeds the continent and the barges that carry it, Mithalenna’s cult with the Temple of the Seven Bowls, and the Cref oath at the old seat. None of it is built. No quest, no chapter, no bridge, no boat, and no way over the main channel below its first third.'),
  'West Mithala': status('early', 'The western entrance and the driest quarter: twenty-four grassland hexes of tall warm-season prairie on deep black river soil, the arm out of the hill country coming in along the Celder margin with a fan of two short distributaries off it, one summer channel, and the emptiest horizon in Azhora - a full circle of it, unbroken except by weather. Hares and harriers on the grass, buffalo on the open rows.',
    'Everybody, and Minora above all: the lore puts the city at the first fork of the Lizeem at the plain’s western entrance, and neither it nor the fork is on the atlas. No settlement, no market, no quest, no chapter.'),
  'East Mithala': status('early', 'The lowest and flattest quarter, and the one the water leaves by: the threads of the main channel gather again here and go out to the sea across the eastern border, in the only wood on the plain - willow, black poplar and alder two and three trees deep on the banks. Rank green grass on the wettest ground in the Mithala, backswamps between the channels, one back channel dry from one year’s end to the next, and the first dark line of the Acorwood on the north-eastern horizon. Otters, herons, egrets and duck on the water, deer in the gallery.',
    'Everybody: the channel-confluence market towns that consolidate the grain, their docks and warehouses, and the boats. No quest, no chapter, and nothing crosses the main channel below its first third.'),
  'North Mithala': status('early', 'The plain going north until it stops being plain: tall grass on a dry shelf in the south, the north braid coming down out of it on two heads with a cross braid joining, one summer channel, and then a long imperceptible fall northward into sedge and rush as the Acor Wetlands begin, with no line anywhere to say where one becomes the other. Geese and wading birds on the fen margin, buffalo and hares on the shelf, a harrier over it.',
    'Everybody, and both of its margins: the wetland communities north of it and the Acorwood, which the lore says the river people have no reason to enter. No settlement, no quest, no chapter.'),
  // The southwestern block (src/southwest-world.js), 2026-09-30: four countries in the driest
  // quarter of the continent, terrain, climate, water, scenery and wildlife only, and nothing that
  // belongs to anybody. **None of the four touches a built country**: the Ibenwood forest belt
  // between them and Nethereum is not built, so until it is they are reached by F8 travel and by
  // nothing else.
  Navarth: status('early', 'The high ground of the southwest: a worn tableland at forty metres with ten rounded swells on it, the four along the western rim standing over a thirty-metre fall into the Ganesh. Hot desert over twenty of its twenty-two hexes, with bare wormwood-and-thorn scrub spaced wide; at the north-eastern tip two Mediterranean hexes carry the block’ one piece of forest and the Ibenwood’ southern edge. The Alezhor Water runs the length of the northern border and is waded anywhere. Hares on the swells, a plateau hawk over the rim, and very little else.',
    'Everybody. Navarth’ whole lore is the Fire Memory practised at a remove from the volcanic ground that made it - the surrogate fires kept where fumaroles would be, the ceremonial records, the pilgrimage south - and its economy is the grey sheep and the wool. None of it is built: no fire, no flock, no settlement, no quest, no chapter, and no way in but F8 until the Ibenwoods are built.'),
  'West Pyros': status('early', 'An open semi-arid plain falling south from the Navarth rim to the sea, with the Vaellir - the second river the atlas draws large, after the Lizeem - running the whole of its eastern border and growing from a wadeable gravel head to a hundred paces of water nobody crosses. Bunch grass in tussocks over most of it, desert scrub on the western columns, a ribbon of poplar and tamarisk on the river, and one green hex at the southern tip where the river reaches the sea. Otters and duck on the water, a river fox in the gallery, hares and a harrier on the plain.',
    'Everybody, and Gala above all: the lore puts the walled Pyrosi capital on a terraced hill above a river confluence in this country, and neither the hill, the terraces nor the confluence is on the atlas. No settlement, no terrace, no fumarole site, no quest, no chapter, and nothing crosses the Vaellir below its ford.'),
  'Ganesh Desert': status('early', 'The first true desert in the game and the largest of these four: thirty-one hexes of hot desert, every one of them BWh, flat to gently rolling, with no canyon and no escarpment anywhere. Wind is the whole of what shapes it - a thin skin of pale sediment over stone, swept to grit on the rises, gathered in the pockets, combed into a long grain on the summer wind’ own bearing. Two dry washes cross it with nothing in either but one damp reach, and on the north-west it runs out at a gulf it is arid right up to. Four ranges of animals in the whole country, which is the honest dry-year reading: two bone-birds in the air, hares on the damp reach, and the ghubr - the Ganesh dustback, the one animal this country’s lore names - working the sediment pockets of the northern margin.',
    'Everybody who crosses it: the caravan waystations at the old water points, the Route Registry at Dinelv that issues the crossing guidance, the pastoral communities that come down from the plain in the wet years. No well, no waystation, no route, no quest, no chapter, and no permanent water in the country at all.'),
  'Ganesh Plain': status('early', 'The transition between the desert and the green south-east, which the lore says behaves as though it cannot decide which it is. Level clay-floored ground crossed by three shallow drainage channels too diffuse to be rivers, with eight closed depressions strung along them where the water gathers and the grass lasts longest - and in a dry year, which is what the world can show, those are the only green on it. A low divide runs down the eastern side; west of it everything goes to the Ganesh, east of it the ground falls to the sea. One Mediterranean hex in the south-eastern corner where Marosh begins.',
    'Everybody: the pastoral communities who read the drought cycle and move by it, their herds, the northern market settlements and Ganesh Ford at the head of them. No market, no settlement, no stock, no quest, no chapter.'),
  // The four Meroshe deserts. The atlas gives all ninety-five hexes `plains` and `BWh`, so what is
  // built in each is a surface rather than a landform, and what is missing from all four is the same
  // thing: everybody. The Moreshi oasis houses, the caravan routes across the sand sea, the water
  // rights, the Route Registry’s crossing guidance and every dustback in the desert are somebody’s.
  'North Meroshe Desert': status('early', 'The rocky northern transition of the great desert, and the one quarter of it that is not sand: a floor of bare bedrock under a skin of gravel, with nine low escarpments crossing it north and south where harder beds outcrop, one to two metres of riser each and a long back slope between. Thorn rooted in the joints of the stone - the only trees in ninety-five hexes - and a bone-bird over it. The Ganesh Plain’s clay runs out into it over ten hex edges with no line anywhere to mark the change, and Marosh’s green Mediterranean hills stand a mile off the eastern edge.',
    'Everybody. The lore’s northern Meroshe is the caravan approach from the plain, the oasis communities at the old water points and the dustback herds that make an oasis house wealthy. None of it is built: no oasis, no well, no route, no cairn, no stock, no quest, no chapter, and no way in but F8.'),
  'West Meroshe Desert': status('early', 'The desert between the Dinelv escarpment and the open western ocean: three coalesced gravel fans spreading south-west off the highland foot, sorted coarse to fine from apex to toe, falling seven metres over four hundred and thirty to a shore it is arid right up to. At the fans’ dead end lies the Malhat, a salt pan three hundred paces across, flat to the centimetre and crusted white - the only visible water in the Meroshe and undrinkable. Gulls off the sea and a bone-bird inland; nothing else.',
    'Everybody, and the whole Dinelv apparatus above it: the plateau road, its garrison, its cisterns and the tariff inspection at the northern pass, and the quarries the Maroshi court contracts. Nothing is built on the fans and nothing at the salt: no road, no cistern, no salt working, no quest, no chapter.'),
  'Central Meroshe Desert': status('early', 'The erg, and the first sand sea in the game: thirty-one hexes of linear dunes running north-west to south-east on the summer wind’s bearing, seven metres floor to crest and two hundred and thirty paces apart, with swept flat gravel corridors between them that are the only fast ground and run only the two ways the ridges do. The whole country sits in a shallow closed sink with no outlet and no river edge anywhere on it, which is why the sand is there. It is the one country in Azhora with no horizon, and the emptiest: one range of animals in thirty-one hexes, and it is in the air.',
    'Everybody who knows the way across. The lore makes navigating the sand seas without local knowledge one of the more reliable methods of dying on Azhora, and the local knowledge, the aquifer-fed oases, the route marks and the caravans are all somebody’s. No oasis, no mark, no track, no quest, no chapter.'),
  'South Meroshe Desert': status('early', 'The reg: a floor of pebbles packed edge to edge over a whole country, varnished dark by iron and manganese, flat enough to see twenty miles across. Thirteen of its hex edges are Trogo’s tropical rainforest and four are the southern ocean, and the fog off both comes in warm and thick and stands for days over ground the atlas still calls hot desert - so the southern third carries a crust, lichen in the lee of every pebble and the only close-standing thorn in the Meroshe, while the north-western third is as bare as anything in Azhora. Three ranges of animals, all of them on the fog.',
    'Everybody: the canyon communities of the deep Moroshe that the lore puts south and east of here, their seeps, their petroglyphs and their trade with the highland, and the fishing settlements on Trogo’s estuaries. No settlement, no seep, no canyon, no quest, no chapter.'),
  // Forty to forty-two, the block's western edge: a cape, a desert plateau and the wet edge of the
  // desert. All three are terrain, climate, water, scenery and wildlife and nothing that belongs to
  // anybody, which on these three countries means a great deal is missing: the cape's whole navigation
  // economy, the entire Dinelv apparatus of city, road, garrisons, quarries and Plateau Watch, and
  // Hama's harbour and its seven merchant houses.
  'Cape Heth': status('early', 'A low desert promontory reaching four hundred metres further west than any other ground in Azhora, with open water on three sides of it - twenty-one hex edges, the most maritime country in the block. Grey-brown marine sandstone soft enough to cut by hand; one low ridge down the spine with a spray-swept western face carrying bare rock, gravel, salt crust and lichen, and a sheltered eastern side with five drainage hollows holding every scrap of soil the cape has. At the point, the only `coast` hex the atlas puts inside any country on the map. Sea-plungers folding into the water off the point, gulls on its rock, waders in the sheltered bight north of it, and hares in the hollows - the only animal on the ground in nineteen hexes.',
    'Everything the lore of this cape is about: the three hundred people at the tip and in the bight, the harbour on the south-eastern face, the cisterns the storms are measured against, the pilots and the salvage, the provisioning trade and the whole navigation-landmark economy of the western sea route. No settlement, no harbour, no cistern, no garden in a hollow, no quest, no chapter.'),
  'Dinelv Highlands': status('early', 'The first desert highland in the game and the high ground of the whole southwest: thirty-five hexes of hot desert standing eighty metres over the cape on one side and the sand deserts on the other. Stepped escarpments with the rock in horizontal bands - warm-toned low, harder and darker above - cut by four seasonal channels, three of which come out at the heads of the Meroshe fans below. On top, six ridge systems on the peninsula’s own north-north-east strike, four gaps through them, four closed basins where the plateau’s water dies, and three flat-topped tables standing sixty and seventy metres over the lot: the only three hot-desert `mountain` hexes on the atlas. One graded ramp up the northern face is the only way a loaded animal can be walked up. A hawk over the rim, a bone-bird over the tables, hares in two of the basins and canyon tortoises in a third.',
    'Everything: the city of Dinelv below the escarpment, the plateau road and the day it takes to climb it, the garrisons at the northern pass and the middle saddle with their cisterns and their tariff inspection, the quarries that cut the warm stone, the ridge-exposure mines, the Plateau Watch, and the pastoral communities who have been on this plateau longer than any of it and move their herds between the water points by season. No road, no garrison, no cistern, no quarry, no mine, no quest, no chapter.'),
  Hama: status('early', 'Where the desert stops. Hama holds the corner of the continent with ocean on the west and ocean on the south, and the atlas splits it in half twice over: nine `grassland` hexes that are every one of them `Csb` on the seaward side, ten `plains` hexes that are every one of them `BWh` inland, and no hex where the two fields disagree. So the seaward two hexes are real winter-rain Mediterranean country - the densest grass in nine countries, evergreen scrub in the hollows, a few trees leaning inland off the sea wind - the inland half is a stony broken rise "rough without being impassable", and the line between them takes about two hundred paces to cross. Three dry winter beds with the greenest grass in the southwest in their floors. Hares in the sward and in a bed, a harrier over the grass, gulls at the corner, and one bone-bird over the dry half that does not cross the line.',
    'Hama Harbour and everything it is for: the Council of Merchant Houses and its seven families, the rotating Speaker, the southern-archipelago trade, the tribute Dinelv collects, the plots on the coastal margin and the food that comes in by sea. No town, no harbour, no plot, no quest, no chapter.'),
  // Marosh and Trogo, the last two countries of the southwest quarter.
  Marosh: status('early', 'The ridge the Meroshe stands behind. Eighteen hexes in a strip two wide down the Iberos face of the peninsula, and the only country in the southwest with no hot desert on it: eight `hills` hexes that are every one of them `Csb` and carry seventeen of its eighteen desert edges, and ten `grassland` hexes that are every one of them `Csa` and carry all twenty of its ocean edges. A single oak-and-maquis crest at seventy-four metres wrings the sea air out, which is why the sand sea begins on the far side of it; below the crest a hot-summer terrace of grass and aromatic scrub falls three hundred metres to the Iberos. One gap through the ridge with the only river the atlas draws on this coast in the bottom of it, four dry winter combes down the seaward face, and the first real wood in the southwest outside the Vaellir\u2019s gallery.',
    'Dinelv the capital and everything the kingdom is: the Route Registry, the Tariff Table, the caravan road over the gap, the waystations and the tribute from Hama. No city, no road, no waystation, no quest, no chapter.'),
  Trogo: status('early', 'The first rainforest in the game. Twenty-two `deep_forest` hexes, `Af` on every one - the wettest code the atlas paints anywhere - with seven `Csa` `grassland` hexes along the exposed southern shore where the forest stops. One hex west is hot desert, and the lore explains both in a sentence: "a ridgeline that catches the southern moisture and drops a fog wall on its windward face while the leeward side stays desert." Two rules belong to this country and nowhere else: a haze of .0144 that hides a traveler at a hundred and twenty paces, and an undergrowth rule that lets a body walk the watercourse, the four gullies, the five animal paths and the five clearings and refuses the thicket between them. Canopy in three layers with a cloud forest on the crest and mangrove where the sheltered shore meets the water.',
    'The three peoples of the ecotone and everything they do: the estuary fishing villages, the timber Hama has been buying for a century, the resin the Maroshi court taxes without understanding what it is taxing, and the forest language nobody has classified. No village, no anchorage, no track, no quest, no chapter.'),  // Still 'edge' on purpose: the country behind the gate is built, but the gate
  // is shut for Chapters 1-2 and the only ways in are the developer tools.
  'East Suval': status('edge', 'Elod’s border post on the stone road: a ditch, a shut gate and its guard in light black armour. Behind it the country is now built — the city of Elod with its Sea-Road Gate, the walled precinct and the Threshold, the ordinary city, the harbour quarter and its quay, twenty-one Elodi and foreigners with something to say, the North Light, Sorrow Beach, Sevenwalls and the dry hills.',
    'A way in. The border stays closed for the main quest, so nothing behind it can be reached except by the F8 tools: the sea passage into the harbour quarter is stubbed (src/east-suval.js, ELOD_SEA_ROUTE) and the Threshold’s admission terms lead nowhere. No quest, no trade, no interiors.'),
});

const known = new Set(Object.keys(BUILD_STATUS));

/** Every region the atlas knows, with how far it is built. Playable regions first, then the rest. */
export function buildStatusList() {
  const rest = REGION_DESIGN.map(entry => entry.id).filter(id => !known.has(id)).sort();
  return [...PLAYABLE_REGIONS.filter(id => known.has(id)), ...[...known].filter(id => !PLAYABLE_REGIONS.includes(id)), ...rest]
    .map(id => regionBuildStatus(id));
}

export function regionBuildStatus(id) {
  const entry = BUILD_STATUS[id] ?? status('unbuilt', '', 'The whole region.');
  const state = BUILD_STATES[entry.state] ?? BUILD_STATES.unbuilt;
  return Object.freeze({ id, state: state.id, label: state.label, colour: state.colour, order: state.order,
    playable: state.order >= 2, detail: entry.detail || state.note, work: entry.work });
}
